name: Playwright Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser and device to test'
        required: true
        default: 'desktop-chromium'
        type: choice
        options:
          - desktop-chromium
          - mobile-chromium
          - desktop-webkit
          - mobile-webkit

jobs:
  test:
    name: Run Playwright Tests - ${{ inputs.browser || 'desktop-chromium' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run quality checks
        run: npm run quality-check

      - name: Run Playwright Tests
        run: |
          case "${{ inputs.browser }}" in
            mobile-chromium)
              npm run mobile-chromium
              ;;
            desktop-webkit)
              npm run desktop-webkit
              ;;
            mobile-webkit)
              npm run mobile-webkit
              ;;
            *)
              npm run desktop-chromium
              ;;
          esac

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ inputs.browser || 'desktop-chromium' }}
          path: playwright-report/
